### ISSUE TITLE
cocos2dVersion is strange

### ISSUE THREAD

**Issue by masteage** [cocos-creator/engine-native#1737]
* why 2.1.0 -> 2.0.x ?????
* https://github.com/cocos-creator/cocos2d-x-lite/blob/fe77b20fe857a0cbfc2efd337b2bec929e7f566c/cocos/cocos2d.cpp#L35

**Comment by minggo** [comment]
@jareguo could you explain it?

**Comment by jareguo** [comment]
Now the version (in repo) is unused. We should sync the version with releases. I will improve our workflow to achieve it. Thanks for the feedback.
