### ISSUE TITLE
声音问题,有个pull requests修改错了

### ISSUE THREAD

**Issue by 284263380** [cocos-creator/engine-native#1958]
AudioEngine.cpp里面函数
AudioEngine::onEnterForeground  
有问题,

有这个   修改如下,
https://github.com/cocos-creator/cocos2d-x-lite/pull/1930/files
但是这个修改也是错的,如下代码是错误的
bool AudioEngineImpl::_checkAudioIdValid(int audioID) {
    auto player = _audioPlayers[audioID];
    return player != nullptr;
}
错误之处是
 auto player = _audioPlayers[audioID];
这句话会在 _audioPlayers 里面添加一个audioID, 这样update的时候就有问题了.

正确修改方法我感觉这样就行了,修改
void AudioEngine::onEnterForeground(const CustomEvent &event) {
    auto itEnd = _breakAudioID.end();
    for (auto it = _breakAudioID.begin(); it != itEnd; ++it) {
        if(_audioIDInfoMap.find(*it) != _audioIDInfoMap.end()){
            _audioEngineImpl->resume(*it);
        }
    }
    _breakAudioID.clear();
}

**Comment by umbrellaPP** [comment]
感谢反馈，我们修复下这个问题
