### ISSUE TITLE
Use a consistent convention for throwing-functions and error-handling that's independed of compiler.

### ISSUE THREAD

**Issue by Jacksparrow2525** [cocos-creator/engine-native#3340]
For example in FrameGraph's implementation;

Resource() noexcept = default;

Was causing issues, between different GCC and Clang.
http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#1778
Some compilers deal with the quirks some not.

A tempororary Kludge was to remove the noexept qualifier in VS2017, 
but the member making the class thowing should be identified and correctly handled

Insight: 
https://stackoverflow.com/questions/29483120/program-with-noexcept-constructor-accepted-by-gcc-rejected-by-clang

**Comment by minggo** [comment]
According the goole's coding style of [except](https://google.github.io/styleguide/cppguide.html#noexcept), i think we'd better only use it in move constructors and the functions that will improve performance.
