### ISSUE TITLE
review 代码发现问题，想确认下

### ISSUE THREAD

**Issue by CarlZhongZ** [cocos-creator/engine-native#3583]
![image](https://user-images.githubusercontent.com/5827910/120068464-69b3c480-c0b3-11eb-84b1-71b1ddefa165.png)

这个代码里 会遍历层数， 但是同步 GL_TEXTURE_2D_ARRAY 的时候设置的深度又是同样的层数，根据 open gl文档描述这个应该有问题吧？我不是很确定，希望能解答我的疑惑

**Comment by CarlZhongZ** [comment]
虽然我知道，这个代码在 ES2 impl 不会被跑到哈

**Comment by YunHsiao** [comment]
嗯嗯，应该是疏忽了，感谢指出

**Comment by YunHsiao** [comment]
这个参数传的是 depth count，zoffset 在 width 前面传的
