### ISSUE TITLE
WebView internal pages call external code failed.

### ISSUE THREAD

**Issue by k888168168** [cocos-creator/engine-native#3625]
https://docs.cocos.com/creator/3.0/manual/en/ui-system/components/editor/webview.html#webview-internal-pages-call-external-code

According this manual,
When I needs to pass data to external code by change `document.location`
Always got crash in Android App.

**Comment by minggo** [comment]
Could you please provide an example? Thanks.

**Comment by k888168168** [comment]
I create a pr to fix this issue
#3644

**Comment by minggo** [comment]
thanks
