### ISSUE TITLE
strdup 会在某些64位android手机造成 segfault

### ISSUE THREAD

**Issue by dunadain** [cocos-creator/engine-native#3661]
请将httpclient-java.cpp中 getBufferFromJString函数改成，不要使用strdup
char *getBufferFromJString(jstring jstr, JNIEnv *env) { //NOLINT(readability-convert-member-functions-to-static)
        if (nullptr == jstr) {
            return nullptr;
        }
        std::string strValue = cc::StringUtils::getStringUTFCharsJNI(env, jstr);
        auto size = strlen(strValue.c_str());
        char *c = (char*)malloc(size + 1);
        strcpy(c, strValue.c_str());
        return c;
    }

**Comment by minggo** [comment]
strdup 具体指的是？
