### ISSUE TITLE
不支持翻转viewport

### ISSUE THREAD

**Issue by Xrysnow** [cocos-creator/engine-native#3687]
vulkan需要翻转viewport的功能，但目前`Viewport`的尺寸为uint类型，无法使用负数尺寸实现翻转
参考：https://www.saschawillems.de/blog/2019/03/29/flipping-the-vulkan-viewport/

**Comment by YunHsiao** [comment]
为什么需要翻转呢？

**Comment by Xrysnow** [comment]
屏幕坐标系和opengl是上下颠倒的，链接中有解释

**Comment by YunHsiao** [comment]
这个上层是不需要关心的，signY 的问题通过修改投影矩阵就解决了，这样做更通用一些。negative viewport 在 vk 1.0 也是扩展，并不是一个非常 portable 的方案，所以就没允许上层用噢。

**Comment by Xrysnow** [comment]
感谢解答
