### ISSUE TITLE
为何win版本的libGLESv2缺少导出函数

### ISSUE THREAD

**Issue by Xrysnow** [cocos-creator/engine-native#3696]
从 https://github.com/cocos-creator/engine-native-external/releases 获取的预编译库中，windows版本的libGLESv2缺少后缀OES/EXT的导出函数，但是mac版本是齐全的。这种情况下引擎是如何调用这些扩展函数的？

**Comment by YunHsiao** [comment]
扩展函数当然并不是所有平台都支持，尤其桌面端目前其实都是借 PVRVFrame 这个第三方库实现的 GLES 转桌面 GL 的。引擎里初始化 device 时会先查询当前平台支持哪些，然后运行时走不同的 code branch。

**Comment by minggo** [comment]
@Xrysnow 是有遇到什么问题吗？

**Comment by Xrysnow** [comment]
因为我看加载时是直接在动态库里取函数地址，但libGLESv2没有导出扩展函数，而个别地方直接调用了扩展函数，比如
https://github.com/cocos-creator/engine-native/blob/10c7d816a7c320836f84541202e30d299a5e2023/cocos/renderer/gfx-gles2/GLES2Context.cpp#L548
所以想确认一下win上的扩展函数是从哪里获得的

**Comment by YunHsiao** [comment]
> libGLESv2没有导出扩展函数

当然有导出，也有加载，你这个结论是从哪来的。。

**Comment by Xrysnow** [comment]
应该是我理解错误了，dumpbin看不到，但不是直接取的。
